### ISSUE TITLE
[BE] Get user/s endpoint

### ISSUE THREAD

**Issue by sirbully** [study-pal/studypal#5]
### Tasks

- `GET` request to `/users` which will return data as an array of tutors if we have query parameter `type=tutor`
- `GET` request to `/user/:id` which will return a specific user object

**Comment by sirbully** [comment]
https://firebase.google.com/docs/firestore/manage-data/add-data#node.js

**Comment by egwilborn** [comment]
@sirbully @sophiedang0101 I added a few more commits that finish this issue if you don't mind reviewing the pull request. 
I had to make some changes to the package.json files to get my local project connected to firebase so if you see those files changed, that's why. Let me know if there are any issues with that.
